### ISSUE TITLE
Configurartion problem

### ISSUE THREAD

**Issue by Yuki-Togawa** [BioinformaticsCSU/SRC#2]
Hello,
I ran the DEMO described in the README and got the following error. It seems that there is a problem with the configuration.
However, I still don't know the root cause of this error, so I would appreciate any advice you can give me.

```
Start Running Spark RepeatClassifier
hadoop-2.7.6/bin/hadoop fs -rm -r /data/spark_classifier/RepeatScout//RepeatLib_ant.fa.tmp
rm: `/data/spark_classifier/RepeatScout//RepeatLib_ant.fa.tmp': No such file or directory
hadoop-2.7.6/bin/hadoop fs -put /work2/togawa/SRC/demo/RepeatLib_ant.fa.tmp /data/spark_classifier/RepeatScout/
put: `/data/spark_classifier/RepeatScout/': No such file or directory
21/07/13 15:49:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/07/13 15:49:49 INFO SparkContext: Running Spark version 3.0.3
21/07/13 15:49:49 INFO ResourceUtils: ==============================================================
21/07/13 15:49:49 INFO ResourceUtils: Resources for spark.driver:

21/07/13 15:49:49 INFO ResourceUtils: ==============================================================
21/07/13 15:49:49 INFO SparkContext: Submitted application: Spark repeat classifier
21/07/13 15:49:49 INFO SecurityManager: Changing view acls to: togawa
21/07/13 15:49:49 INFO SecurityManager: Changing modify acls to: togawa
21/07/13 15:49:49 INFO SecurityManager: Changing view acls groups to:
21/07/13 15:49:49 INFO SecurityManager: Changing modify acls groups to:
21/07/13 15:49:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(togawa); groups with view permissions: Set(); users  with modify permissions: Set(togawa); groups with modify permissions: Set()
21/07/13 15:49:49 INFO Utils: Successfully started service 'sparkDriver' on port 36451.
21/07/13 15:49:49 INFO SparkEnv: Registering MapOutputTracker
21/07/13 15:49:49 INFO SparkEnv: Registering BlockManagerMaster
21/07/13 15:49:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
21/07/13 15:49:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
21/07/13 15:49:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
21/07/13 15:49:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-18dd48f0-cf07-41ed-8594-f71cbaae4f38
21/07/13 15:49:49 INFO MemoryStore: MemoryStore started with capacity 5.2 GiB
21/07/13 15:49:49 INFO SparkEnv: Registering OutputCommitCoordinator
21/07/13 15:49:49 INFO Utils: Successfully started service 'SparkUI' on port 4040.
21/07/13 15:49:49 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://nazuna.local:4040
21/07/13 15:49:49 WARN SparkContext: Please ensure that the number of slots available on your executors is limited by the number of cores to task cpus and not another custom resource. If cores is not the limiting resource then dynamic allocation will not work properly!
21/07/13 15:49:49 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: Invalid master URL: spark://master_ip:7077
        at org.apache.spark.util.Utils$.extractHostPortFromSparkUrl(Utils.scala:2399)
        at org.apache.spark.rpc.RpcAddress$.fromSparkURL(RpcAddress.scala:47)
        at org.apache.spark.deploy.client.StandaloneAppClient.$anonfun$masterRpcAddresses$1(StandaloneAppClient.scala:52)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at org.apache.spark.deploy.client.StandaloneAppClient.<init>(StandaloneAppClient.scala:52)
        at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.start(StandaloneSchedulerBackend.scala:122)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:201)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:562)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)
21/07/13 15:49:50 INFO SparkUI: Stopped Spark web UI at http://nazuna.local:4040
21/07/13 15:49:50 INFO StandaloneSchedulerBackend: Shutting down all executors
21/07/13 15:49:50 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
21/07/13 15:49:50 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/07/13 15:49:50 INFO MemoryStore: MemoryStore cleared
21/07/13 15:49:50 INFO BlockManager: BlockManager stopped
21/07/13 15:49:50 INFO BlockManagerMaster: BlockManagerMaster stopped
21/07/13 15:49:50 WARN MetricsSystem: Stopping a MetricsSystem that is not running
21/07/13 15:49:50 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/07/13 15:49:50 INFO SparkContext: Successfully stopped SparkContext
Traceback (most recent call last):
  File "/work2/togawa/SRC/src_main.py", line 66, in <module>
    sc = SparkContext(conf=conf)
  File "/home/togawa/work2/SRC/spark-3.0.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/context.py", line 135, in __init__
  File "/home/togawa/work2/SRC/spark-3.0.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/context.py", line 198, in _do_init
  File "/home/togawa/work2/SRC/spark-3.0.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/context.py", line 317, in _initialize_context
  File "/home/togawa/work2/SRC/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1568, in __call__
  File "/home/togawa/work2/SRC/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Invalid master URL: spark://master_ip:7077
        at org.apache.spark.util.Utils$.extractHostPortFromSparkUrl(Utils.scala:2399)
        at org.apache.spark.rpc.RpcAddress$.fromSparkURL(RpcAddress.scala:47)
        at org.apache.spark.deploy.client.StandaloneAppClient.$anonfun$masterRpcAddresses$1(StandaloneAppClient.scala:52)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at org.apache.spark.deploy.client.StandaloneAppClient.<init>(StandaloneAppClient.scala:52)
        at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.start(StandaloneSchedulerBackend.scala:122)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:201)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:562)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)

21/07/13 15:49:50 INFO ShutdownHookManager: Shutdown hook called
21/07/13 15:49:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-ad622eaa-86d1-438a-8cef-dfc83d3ee3bb
21/07/13 15:49:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-dcb2a6b0-99d1-4814-895e-3a1f1b684375
total_executor_cores: 240, Spark classifier running time: 16.63555 s
```

**Comment by Yuki-Togawa** [comment]
I would like to know more about "`/data/spark_classifier/RepeatScout/`" in the hdfs directory configuration.

**Comment by CSU-KangHu** [comment]
Hi,  Yuki-Togawa. I'm sorry to see your problem after two months, and I am really sorry for the trouble caused by the configuration problem. I will update README with a more detailed explanation immediately and attach my configuration process so that other users will not be hindered.

At the same time, I checked the configuration item again and found that the HDFS dir configuration item is redundant. Therefore, I updated configuration.py. Please clone the new version of the code.

The following is my configuration process. Please configure it according to your actual situation.
 
![1632903344(1)](https://user-images.githubusercontent.com/22925278/135235924-65b20985-5cca-4325-903b-8ed3eb62dc5c.png)


According to your error log,
`org.apache.spark.SparkException: Invalid master URL: spark://master_ip:7077`
You made an error when configuring the Spark Master Address. In my cluster, the master IP address is **node1014**, and my spark port is the default **7077**, so my input is _spark://node1014:7077_, you need to configure it according to the actual master IP address and the port of your cluster.
I will update the README immediately. If you have any questions, you can contact me directly by email, kanghu@csu.edu.cn.

**Comment by CSU-KangHu** [comment]
> I would like to know more about "`/data/spark_classifier/RepeatScout/`" in the hdfs directory configuration.

This hdfs directory is used to store some intermediate results of SRC processing.  I choose the pathname at will. In fact, it has no special meaning. You can change it to any path.
